[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="_csrf" type="org.springframework.security.web.csrf.CsrfToken" --]
[#-- @ftlvariable name="userDetails" type="com.ilemontech.ldcos.cloud.configure.security.SecurityUserDetails" --]
[#-- @ftlroot "../resources/templates" --]
